In [1]:
import numpy as np

In [11]:
a=[1,321,34]    #this is list not np.array
b=np.sin(a)
c=np.cos(a)
print(b)
print(c)

[0.84147098 0.52910827 0.52908269]
[ 0.54030231  0.84855433 -0.84857027]


#### we can perform addition subtraction multiplication exponentiation on all the matrices of all dimensions

#### LINEAR ALGEBRA

In [7]:
a=np.ones((2,3))
b=np.full((3,4),2)
print(np.matmul(a,b)) # matrix multiplication ,1st matrix columns= 2nd matrix rows



[[6. 6. 6. 6.]
 [6. 6. 6. 6.]]


In [5]:
#find the determinant
c=np.identity(3)
print(np.linalg.det(c))


1.0
