In [ ]:
import numpy as np

In [50]:
a=np.array([[1,2,3,4,5,6],
            [7,8,9,10,11,12]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [32]:
print(a[1,5])

12


In [33]:
#get a specific row 
print(a[0])

[1 2 3 4 5 6]


In [34]:
#get a specific column
a[:,3]

array([ 4, 10])

In [37]:
#getting fancy[start index:endindex:step size]
a[0,0:4:2]

array([1, 3])

In [47]:
a[0,:]=[9,9,9,9,9,9]

In [51]:
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
#3d array

In [3]:
b=np.array([[[1,2,3,4,5],[5,5,5,5,5]],[[1,1,1,1,1],[2,2,2,2,2]]])
print(b.shape)

(2, 2, 5)


In [5]:
print(b[0,0,2])

3


In [ ]:
#indexing
print(b[0,0,1:4:2])

[2 4]


In [12]:
#all zeros matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
#all 1s matrix
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [20]:
#random decimal numbers
np.random.rand(4,2)

array([[0.25310612, 0.49005404],
       [0.09398881, 0.58573801],
       [0.1180876 , 0.90263848],
       [0.9397846 , 0.22401472]])

In [26]:
#random integer vallues
np.random.randint(9, size=(3,5))

array([[4, 3, 7, 8, 2],
       [2, 0, 3, 1, 5],
       [2, 0, 8, 2, 7]], dtype=int32)

In [28]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
out=np.ones((5,5))
print(out)
z=np.zeros((3,3))
z[1,1]=9
print(z)
out[1:4,1:4]=z
print(out)




[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


###### it  is very tough to make aaray

In [ ]:
# a=[1,2,3]
# b=a
# b[0]=100 #chnage value of b 
# print(a)
# print(a)
#same thing appears beacuse b=a means point at the same thing so 1 chnage in b a changes 
a=[1,2,3]
b=a.copy()#use .copy()
b[1]=54
a


[1, 2, 3]